### PR TITLE
Replaced TSLint for ESLint

### PR DESCRIPTION
**Pull request by yooouuri**
TSLint will be deprecated
~~Also replaced npm with yarn~~
Added .editorconfig

### CODE REVIEW

**Comment by toonvanstrijp** [comment]
@yooouuri thanks for your contribution, everything looks fine except one thing, why use yarn instead of npm? :)

**Comment by yooouuri** [comment]
@ToonvanStrijp I changed from npm to Yarn a long time ago, because back then npm does not have a package-lock file. Never changed back...

**Comment by toonvanstrijp** [comment]
@yooouuri back then yarn was faster indeed, but currently it doesn't really matter that much so I would rather stay at npm, If you could change that I'll merge this ;)

**Comment by yooouuri** [comment]
@ToonvanStrijp done!

**Review by toonvanstrijp — APPROVED** [review]

**Comment by toonvanstrijp** [comment]
@yooouuri thank you! :)

**Pull request merged**
